#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import argparse
import datetime as dt
import pandas as pd
from lib.simulator import PortfolioSimulator

# Setup matplotlib for headless plotting
#import matplotlib
#matplotlib.use('Svg')
#import matplotlib.pyplot as plt
#from matplotlib.finance import candlestick_ohlc
#plt.style.use('ggplot')
import plotly
import plotly.graph_objs as go

parser = argparse.ArgumentParser()
parser.add_argument('stock_path', metavar='STOCK', help='path to the stock rates dataset')
parser.add_argument('actions_path', metavar='ACTIONS', help='path to the timestep to action mapping generated by the strategy')
parser.add_argument('--investment', metavar='AMOUNT', type=float, default='1000', help='initial investment (default: 1000)')
parser.add_argument('--reinvest-rate', metavar='RATE', type=float, default='0.5', help='reinvest rate (default: 0.5)')

args = parser.parse_args()

# Parse UTC timestamp and use time col as index
def set_time_index(df):
    df['timestamp'] = df['time']
    df['time'] = pd.to_datetime(df['time'], unit='s', origin='unix')
    df = df.set_index('time')
    return df

print('Loading stock rates from {} ...'.format(args.stock_path))
stock_df = pd.read_csv(args.stock_path)
stock_df = set_time_index(stock_df)
print(stock_df.head())

print('\nLoading actions from {} ...'.format(args.actions_path))
actions_df = pd.read_csv(args.actions_path)
actions_df = set_time_index(actions_df)
print(actions_df.head())

print('\nMerging dataframes ...')
simulation_df = pd.concat([stock_df, actions_df], axis=1, join='inner')
print(simulation_df.head())

print('Simulating ...')
portfolio = PortfolioSimulator(fees_percent=0.25)
portfolio.set_balance('BTC', 0)
portfolio.set_balance('USD', args.investment)

btc_balance_history = []
usd_balance_history = []
profit_history = []
total_value = []
X = []

import math, random

for row in simulation_df.itertuples():
    print('{} closing at {} -> {}'.format(row[0], row.close, row.action))

    if row.action == 'BUY':
        btc_qty = portfolio.get_balance('USD') / row.close
        portfolio.buy('BTC-USD', btc_qty, row.close)

    elif row.action == 'SELL':
        btc_qty = portfolio.get_balance('BTC')
        portfolio.sell('BTC-USD', btc_qty, row.close)

    btc_balance_history.append(portfolio.get_balance('BTC'))
    usd_balance_history.append(portfolio.get_balance('USD'))
    profit_history.append(portfolio.get_balance('profit'))
    total_value.append(portfolio.get_balance('profit') + portfolio.get_balance('USD') + portfolio.get_balance('BTC') * row.close)
    X.append(row[0])

print('\nSimulation done')
print('---------------')
print('Initial BTC balance: {}'.format(0))
print('Initial USD balance: {}'.format(args.investment))
print('Final BTC balance: {}'.format(portfolio.get_balance('BTC')))
print('Final BTC balance: {} USD (at close price)'.format(portfolio.get_balance('BTC') * simulation_df['close'][-1]))
print('Final USD balance: {}'.format(portfolio.get_balance('USD')))
print('Profit: {}'.format(portfolio.get_balance('profit')))

print('\nPlotting ...')
#fig, axarr = plt.subplots(3, sharex=True, figsize=(16,9))

# Plot stock
trace1 = go.Candlestick(x=simulation_df.index.values, open=simulation_df.open, high=simulation_df.high, low=simulation_df.low, close=simulation_df.close)
trace2 = go.Scatter(x=X, y=btc_balance_history)
trace3 = go.Scatter(x=X, y=usd_balance_history)
trace4 = go.Scatter(x=X, y=total_value)

fig = plotly.tools.make_subplots(rows=4, cols=1)

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 2, 1)
fig.append_trace(trace3, 3, 1)
fig.append_trace(trace4, 4, 1)
#fig['layout'].update(height=600, width=600, title='i <3 subplots')

#plotly.offline.plot({
#    "data": [trace],
#    "layout": go.Layout(title="hello world")
#})
plotly.offline.plot(fig)

#axarr[0].set_title('BTC price over time')
#axarr[0].set_ylabel('USD')
#
#ohlc = []
#for row in stock_df.itertuples():
#    ohlc.append([row.timestamp, row.open, row.high, row.low, row.close, row.volume])
#candlestick_ohlc(axarr[0], ohlc)
#
## Plot balances
#X = stock_df['timestamp']
#axarr[1].set_title('Balances over time')
#axarr[1].grid(b=False)
#ax_usd = axarr[1]
#ax_btc = axarr[1].twinx()
#ax_usd.plot(X, usd_balance_history, 'b-', label='USD')
#ax_usd.set_ylabel('USD')
#ax_btc.plot(X, btc_balance_history, 'r-', label='BTC')
#ax_btc.set_ylabel('BTC')
#
## Plot profit
#axarr[2].set_title('Profit over time')
#axarr[2].plot(X, profit_history)
#axarr[2].set_ylabel('USD')
#
#
#plt.savefig('test.svg')
#
